#!/usr/bin/env bash
#    ____  _   _            _    _ _____               _    
#   / / / | | | | __ _  ___| | _| |_   _| __ __ _  ___| | __
#  / / /  | |_| |/ _` |/ __| |/ / | | || '__/ _` |/ __| |/ /
#  \ \ \  |  _  | (_| | (__|   <| | | || | | (_| | (__|   < 
#   \_\_\ |_| |_|\__,_|\___|_|\_\ | |_||_|  \__,_|\___|_|\_\
#   "return of dreams come true"|_|                         
# ------------------------------------------------------------
###########################################################################               
# Version           : 2022.1
# Author            : HackTrack Team (HackTrack) <team@hacktracklinux.org>
# Licenced          : Copyright 2017-2022 GNU GPLv3
# Website           : https://www.hacktrackgnulinux.org/
###########################################################################
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# .
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# .
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

package=hexinject
version="Upload Source Version 1.6"
figlet $package
echo " Set Remote... "
git remote set-url origin git@github.com:hacktrackgnulinux/$package.git
echo " Pull Request Github... "
git pull
echo " Git Add Local... "
git add -A
echo " Git Commit Local... "
git commit -am "Update $version"
echo " Git Push Local to Github... "
git push
echo " Berhasil... "
